apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops-demo
resources:
  - ../../base
replicas:
  - name: fastapi-demo
    count: 2
images:
  - name: gitops-fastapi
    newName: gitops-fastapi
    newTag: 1.0.0
